---
title: "Fitting O/D-RAPM Model"
format: pdf
---

```{r, load_packages}
library('glmnet')
library('tidyverse')
```

Load the design matrix
```{r, load_data}
design <- read_csv('design_matrices/odrapm_design.csv.gz')
design$...1 <- NULL
design %>% as.matrix() -> design

read_csv('data/processed_data_2022.csv')['PM'] %>% as.matrix() -> pm
```

Fit a GLM model. Set shrinkage for signed intercept to 0.
```{r}
cvfit <- cv.glmnet(
    design, pm, 
    alpha=0, 
    intercept=FALSE, 
    penalty.factor=c(0, rep(1, 434)),
#    lambda=c(100, 500, 1000, 1500, 2000, 2500, 3000)
    lambda=c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
)

```

Change the model to tone down regularization (MSE is the same)
```{r}
model <- glmnet(
    design, pm, 
    alpha=0, 
    intercept=FALSE, 
    penalty.factor=c(0, rep(1, 434)),
#    lambda=c(100, 500, 1000, 1500, 2000, 2500, 3000)
    lambda=50
)
```

Extract coefficients
```{r}
coef(cvfit) %>%
    as.matrix() -> coefs

write.csv(coefs, 'results/coefficients.csv')
```