---
title: "rapm_work"
output: html_document
date: "2024-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
summary(cars)
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(corrplot)
library(ggthemes)
library(kableExtra)
library(gridExtra)
library(kknn)
library(yardstick)
library(dplyr)
library(themis)
library(forcats)
library(xgboost)
library(naniar)
library(vip)
```
## Loading processed data

```{r pressure, echo=FALSE}
processed_data <- read.csv('data/processed_data_2022.csv')
head(processed_data)
```

## Loading design matrix

```{r pressure, echo=FALSE}
design_matrix <- read.csv('design.csv')
dim(design_matrix)
```

## Create dataset with predictors and column to be predicted

```{r pressure, echo=FALSE}
combined_df <- cbind(design_matrix, processed_data['PM'])[,-c(1)]
dim(combined_df)
```

## Create & bake recipe for predicting PM

```{r}
pm_recipe <- recipe(PM ~ ., data = combined_df)
pm_recipe %>% step_rm("PM")
prep(pm_recipe) %>% bake(combined_df)
```

## Creating k-fold validation object

```{r}
# 5 fold cross validation object
folds <- vfold_cv(combined_df, v = 5)
```

## Model fitting

```{r}
# initialize ridge regression model object
ridge_model <- linear_reg(penalty = tune(), mixture = 0) %>% 
  set_mode("regression") %>% 
  set_engine("glmnet")

# ridge regression model workflow
ridge_wflow <- workflow() %>%
  add_model(ridge_model) %>% 
  add_recipe(pm_recipe)

# ridge grid
ridge_grid <- grid_regular(penalty(range = c(-2,2)), levels = 100)

# ridge regression model
ridge_tune <- tune_grid(
  ridge_wflow,
  resamples = folds,
  grid = ridge_grid
)

autoplot(ridge_tune, metric = 'rmse')

best_params <- select_best(ridge_tune, "rmse")
print(best_params)

# Finalize the workflow with the best parameters
final_workflow <- finalize_workflow(ridge_wflow, best_params)

# Fit the finalized workflow on the training data
final_model <- fit(final_workflow, data = combined_df)

# Extract the fitted model from the workflow
fitted_glmnet_model <- extract_fit_engine(final_model)

# Retrieve the coefficients
coefficients <- coef(fitted_glmnet_model, s = best_params$penalty)
print(coefficients)
```

```{r}
print(paste0('Max RAPM coefficient: ', max(coefficients)))
print(paste0('Min RAPM coefficient: ', min(coefficients)))
```

```{r}
sort(coefficients, descending = TRUE)
```


